---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: maven
spec:
  # workspaces:
  # - name: maven-repo
  inputs:
    params:
    - name: GOALS
      description: The Maven goals to run
      type: array
      default: ["package"]
    # - name: MAVEN_SETTINGS_CONFIGMAP
    #   description: The configmap containing Maven settings.xml
    #   type: string
    #   default: maven-settings
    resources:
    - name: source
      type: git
  steps:
    - name: mvn
      #image: gcr.io/cloud-builders/mvn
      image: quay.io/quarkus/centos-quarkus-maven:19.3.1-java8
      #image: maven:3.6.0-jdk-8-slim
      #image: image-registry.openshift-image-registry.svc:5000/ci-cd/maven36-with-tools:latest
      workingDir: /workspace/source
      command: ["mvn"]
      # command: ["/usr/bin/mvn"]
      args:
        # - -Dmaven.repo.local=$(workspaces.maven-repo.path)
        # - -s
        # - /var/config/settings.xml
        - -f
        - code/pom.xml
        - "$(inputs.params.GOALS)"
      volumeMounts:
        - name: maven-settings
          mountPath: /var/config
  # volumes:
  #   - name: maven-settings
  #     configMap:
  #       name: $(inputs.params.MAVEN_SETTINGS_CONFIGMAP)