apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: backend-build-pipeline
  name: backend-build-pipeline
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: {}
  output: {}
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: build
    git:
      ref: master
      uri: https://gitlab.com/ocp-demo/backend_quarkus.git
    # sourceSecret:
    #   name: gogs-secret
    type: Git
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
      env:
        - name: DEV_PROJECT
          value: dev
        - name: CICD_PROJECT
          value: ci-cd
        # - name: BACKEND_URL
        #   value: https://httpbin.org/status/200
        - name: PRIVATE_REGISTRY
          value: http://nexus3:8081/repository/
        - name: REGISTRY
          value: http://nexus3:8081/repository/npm-group
    type: JenkinsPipeline
  successfulBuildsHistoryLimit: 5
  triggers: []
status:
  lastVersion: 1
