---
apiVersion: "v1"
kind: "List"
items:
- apiVersion: "v1"
  kind: "ServiceAccount"
  metadata:
    labels:
      app: "backend"
      version: "1.0.0-SNAPSHOT"
      group: "voravit"
    name: "backend"
- apiVersion: "v1"
  kind: "Service"
  metadata:
    labels:
      app: "backend"
      version: "1.0.0-SNAPSHOT"
      group: "voravit"
    name: "backend"
  spec:
    ports:
    - name: "http"
      port: 8080
      targetPort: 8080
    selector:
      app: "backend"
      version: "1.0.0-SNAPSHOT"
      group: "voravit"
    type: "ClusterIP"
- apiVersion: "apps/v1"
  kind: "Deployment"
  metadata:
    labels:
      app: "backend"
      version: "1.0.0-SNAPSHOT"
      group: "voravit"
    name: "backend"
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: "backend"
        version: "1.0.0-SNAPSHOT"
        group: "voravit"
    template:
      metadata:
        labels:
          app: "backend"
          version: "1.0.0-SNAPSHOT"
          group: "voravit"
      spec:
        containers:
        - env:
          - name: "KUBERNETES_NAMESPACE"
            valueFrom:
              fieldRef:
                fieldPath: "metadata.namespace"
          image: "voravit/backend:1.0.0-SNAPSHOT"
          imagePullPolicy: "IfNotPresent"
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: "/health/live"
              port: 8080
              scheme: "HTTP"
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          name: "backend"
          ports:
          - containerPort: 8080
            name: "http"
            protocol: "TCP"
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: "/health/ready"
              port: 8080
              scheme: "HTTP"
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
        serviceAccount: "backend"
